//! `TerminusFont`: the [`Metrics`] implementer over the embedded, generated
//! Terminus subset (packet/terminus-font, Task 2). See
//! `docs/superpowers/specs/2026-08-21-terminus-font-design.md` §2 for the
//! full design; this module is the hand-written half (the data itself is
//! [`super::terminus_glyphs`], generated by `tools/gen-terminus-glyphs.py`).
//!
//! ## Snapping, not scaling
//!
//! The old `BitmapFont` (font this packet retired, packet/terminus-font)
//! scaled one design cell CONTINUOUSLY to any `size_px` (`scale = size_px /
//! cell_height`). That model is wrong for Terminus, which ships five
//! discrete, individually-hinted bitmaps (12/16/20/24/32px) rather than one
//! shape to rescale. `TerminusFont` therefore does not scale at all: every
//! `Metrics` method (and [`TerminusFont::glyph`]) first snaps the requested
//! `size_px` to the NEAREST of the five embedded buckets via
//! [`nearest_terminus_size`], then returns that bucket's real, pinned
//! ascent/descent/line-height/advance (or glyph rows) — never a linear
//! interpolation of them. `ascent`/`descent`/`line_height`/`advance` are
//! therefore step functions of `size_px`, not continuous ones — a real,
//! deliberate divergence from `BitmapFont`'s old contract; a request for
//! `18.5px` gets EXACTLY the 20px bucket's numbers, not something in
//! between.
//!
//! [`nearest_terminus_size`] is `pub(crate)` because it is the SINGLE
//! canonical implementation of the snap-to-nearest-bucket rule, reused
//! verbatim by [`super::text_render_px`] (Task 4) so the two never disagree
//! on which bucket a given `size_px` resolves to.

use super::terminus_glyphs::{self, GlyphRows};
use super::Metrics;
use crate::style::computed::FontWeight;

/// The 5 embedded pixel-size buckets, ascending — re-exported from the
/// generated module so this file has one name for it too, without a second
/// copy of the literal list.
const SIZES: [f32; 5] = terminus_glyphs::SIZES;

/// Pinned, per-bucket `(ascent, descent, line_height, advance)`, in pixels —
/// real values read directly off each size's BDF source (design doc's
/// "Current state" table), NOT a scaled formula. Index `i` lines up with
/// `SIZES[i]`.
const METRICS: [(f32, f32, f32, f32); 5] = [
    (10.0, 2.0, 12.0, 6.0),  // 12px
    (12.0, 4.0, 16.0, 8.0),  // 16px (default; numerically identical to the
    // old `BitmapFont::vga_8x16()` at 16px — see the design doc §3)
    (16.0, 4.0, 20.0, 10.0), // 20px
    (19.0, 5.0, 24.0, 12.0), // 24px
    (26.0, 6.0, 32.0, 16.0), // 32px
];

/// Snap `px` to the nearest of the 5 embedded Terminus buckets
/// (`docs/superpowers/specs/2026-08-21-terminus-font-design.md` §2's rule,
/// the single canonical implementation — [`super::text_render_px`] delegates
/// here too, Task 4).
///
/// - `px <= 12.0` clamps up to `12.0`; `px >= 32.0` clamps down to `32.0`.
/// - Otherwise `px` falls strictly between two adjacent buckets: pick the
///   nearer one; on an EXACT midpoint (`14.0`, `18.0`, `22.0`, `28.0`),
///   round UP to the larger (more legible) bucket — generalizing
///   `text_render_px`'s old "never shrink below legible" floor from "always
///   floor to 16" to "always break a tie toward more legible."
///
/// Total: non-finite `px` (`NaN`, `+INFINITY`, `-INFINITY`) degrades to a
/// defined, finite bucket (`16.0`, the default size) rather than
/// propagating or panicking.
pub(crate) fn nearest_terminus_size(px: f32) -> f32 {
    if !px.is_finite() {
        return 16.0;
    }
    if px <= SIZES[0] {
        return SIZES[0];
    }
    if px >= SIZES[SIZES.len() - 1] {
        return SIZES[SIZES.len() - 1];
    }
    for w in SIZES.windows(2) {
        let (lo, hi) = (w[0], w[1]);
        if px >= lo && px <= hi {
            let mid = (lo + hi) / 2.0;
            return if px <= mid { lo } else { hi };
        }
    }
    // Unreachable given the clamps above (every finite px in (SIZES[0],
    // SIZES[last]) falls into exactly one window), but total regardless.
    16.0
}

/// Index of `snapped` (assumed to be an exact [`SIZES`] value, i.e. already
/// passed through [`nearest_terminus_size`]) within [`SIZES`]/[`METRICS`].
/// Total: an unexpected/non-bucket value (should not happen by
/// construction) falls back to index `1` (the 16px default) rather than
/// panicking.
fn bucket_of(snapped: f32) -> usize {
    SIZES.iter().position(|&s| s == snapped).unwrap_or(1)
}

/// The `Metrics` implementer over the embedded Terminus subset. Stateless —
/// all real data lives in the generated `const` tables
/// ([`super::terminus_glyphs`]) — so `TerminusFont` is a zero-sized marker
/// type, cheap to construct at every call site.
#[derive(Debug, Clone, Copy, Default)]
pub struct TerminusFont;

/// Max cell height across the 5 embedded buckets (`32`, the 32px bucket) —
/// bounds [`Glyph::rows`]'s fixed-size array so glyph lookup never needs to
/// allocate.
const MAX_CELL_H: usize = 32;

/// One resolved, RENDER-READY glyph: the bucket's cell size, plus its rows
/// widened to a uniform `u16` (a free `as u16` cast from the generator's
/// mixed `u8`/`u16` storage — see [`super::terminus_glyphs`]'s own doc
/// comment for why storage stays byte-tight while this API stays simple).
/// Only the first `cell_h` entries of `rows` are meaningful; the rest are
/// zero padding up to [`MAX_CELL_H`].
#[derive(Debug, Clone, Copy)]
pub struct Glyph {
    pub cell_w: u8,
    pub cell_h: u8,
    pub rows: [u16; MAX_CELL_H],
}

impl TerminusFont {
    pub fn new() -> Self {
        TerminusFont
    }

    /// Look up `ch` at `weight`/`size_px` (`size_px` is snapped to the
    /// nearest bucket internally — see [`nearest_terminus_size`]). Total
    /// over all of `char` and all of `size_px`: an out-of-subset `ch`
    /// resolves to the embedded fallback box (see
    /// `super::terminus_glyphs::lookup`'s own doc comment) rather than
    /// panicking or vanishing.
    pub fn glyph(&self, ch: char, weight: FontWeight, size_px: f32) -> Glyph {
        let snapped = nearest_terminus_size(size_px);
        let g = terminus_glyphs::lookup(snapped, weight, ch);
        let mut rows = [0u16; MAX_CELL_H];
        match g.rows {
            GlyphRows::Narrow(src) => {
                for (dst, &b) in rows.iter_mut().zip(src.iter()) {
                    *dst = b as u16;
                }
            }
            GlyphRows::Wide(src) => {
                for (dst, &w) in rows.iter_mut().zip(src.iter()) {
                    *dst = w;
                }
            }
        }
        Glyph { cell_w: g.cell_w, cell_h: g.cell_h, rows }
    }
}

impl Metrics for TerminusFont {
    fn ascent(&self, size_px: f32) -> f32 {
        METRICS[bucket_of(nearest_terminus_size(size_px))].0
    }

    fn descent(&self, size_px: f32) -> f32 {
        METRICS[bucket_of(nearest_terminus_size(size_px))].1
    }

    fn line_height(&self, size_px: f32) -> f32 {
        METRICS[bucket_of(nearest_terminus_size(size_px))].2
    }

    /// Monospace, like `BitmapFont`: every character shares the bucket's
    /// single advance width. `ch` is deliberately never inspected (total
    /// over all of `char` by construction, same contract `BitmapFont::
    /// advance` already guaranteed).
    fn advance(&self, _ch: char, size_px: f32) -> f32 {
        METRICS[bucket_of(nearest_terminus_size(size_px))].3
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // --------------------------------------------------- nearest_terminus_size

    #[test]
    fn exact_bucket_values_map_to_themselves() {
        for &s in &SIZES {
            assert_eq!(nearest_terminus_size(s), s, "size={s}");
        }
    }

    #[test]
    fn exact_midpoints_round_up() {
        assert_eq!(nearest_terminus_size(14.0), 16.0);
        assert_eq!(nearest_terminus_size(18.0), 20.0);
        assert_eq!(nearest_terminus_size(22.0), 24.0);
        assert_eq!(nearest_terminus_size(28.0), 32.0);
    }

    #[test]
    fn interior_non_midpoint_values_land_on_the_nearer_bucket() {
        assert_eq!(nearest_terminus_size(13.0), 12.0);
        assert_eq!(nearest_terminus_size(15.0), 16.0);
        assert_eq!(nearest_terminus_size(19.0), 20.0);
        assert_eq!(nearest_terminus_size(30.0), 32.0);
    }

    #[test]
    fn below_min_and_above_max_clamp() {
        assert_eq!(nearest_terminus_size(0.0), 12.0);
        assert_eq!(nearest_terminus_size(11.9), 12.0);
        assert_eq!(nearest_terminus_size(32.1), 32.0);
        assert_eq!(nearest_terminus_size(1000.0), 32.0);
    }

    #[test]
    fn non_finite_input_degrades_to_a_defined_finite_bucket() {
        for size in [f32::NAN, f32::INFINITY, f32::NEG_INFINITY] {
            let out = nearest_terminus_size(size);
            assert!(out.is_finite(), "nearest_terminus_size({size}) = {out} was not finite");
            assert_eq!(out, 16.0);
        }
    }

    // --------------------------------------------------------------- Metrics

    #[test]
    fn metrics_at_each_bucket_match_the_pinned_table_exactly() {
        let f = TerminusFont::new();
        let expected: [(f32, f32, f32, f32, f32); 5] = [
            (12.0, 10.0, 2.0, 12.0, 6.0),
            (16.0, 12.0, 4.0, 16.0, 8.0),
            (20.0, 16.0, 4.0, 20.0, 10.0),
            (24.0, 19.0, 5.0, 24.0, 12.0),
            (32.0, 26.0, 6.0, 32.0, 16.0),
        ];
        for (size, ascent, descent, line_height, advance) in expected {
            assert_eq!(f.ascent(size), ascent, "ascent at {size}");
            assert_eq!(f.descent(size), descent, "descent at {size}");
            assert_eq!(f.line_height(size), line_height, "line_height at {size}");
            assert_eq!(f.advance('A', size), advance, "advance at {size}");
        }
    }

    #[test]
    fn non_bucket_size_resolves_metrics_as_the_snapped_bucket() {
        let f = TerminusFont::new();
        // 18.5 snaps to 20.0 (nearer than 16.0) -- proves the step-function
        // (not continuous-scaling) contract.
        assert_eq!(f.ascent(18.5), f.ascent(20.0));
        assert_eq!(f.descent(18.5), f.descent(20.0));
        assert_eq!(f.line_height(18.5), f.line_height(20.0));
        assert_eq!(f.advance('x', 18.5), f.advance('x', 20.0));
    }

    #[test]
    fn totality_on_unusual_size_px_no_panic() {
        let f = TerminusFont::new();
        for size in [0.0, -1.0, f32::NAN, f32::INFINITY, f32::NEG_INFINITY, f32::MIN, f32::MAX] {
            assert!(f.advance('A', size).is_finite());
            assert!(f.ascent(size).is_finite());
            assert!(f.descent(size).is_finite());
            assert!(f.line_height(size).is_finite());
            let g = f.glyph('A', FontWeight::Normal, size); // must not panic
            assert!(g.cell_w > 0 && g.cell_h > 0);
        }
    }

    // ----------------------------------------------------------------- glyph

    #[test]
    fn glyph_widens_narrow_rows_to_u16_uniformly() {
        let f = TerminusFont::new();
        let g = f.glyph('A', FontWeight::Normal, 16.0);
        assert_eq!(g.cell_w, 8);
        assert_eq!(g.cell_h, 16);
        assert_eq!(g.rows[2], 0x3C);
        assert_eq!(g.rows[7], 0x7E);
        // Padding past cell_h stays zero.
        assert_eq!(g.rows[16], 0);
        assert_eq!(g.rows[31], 0);
    }

    #[test]
    fn glyph_at_a_wide_bucket_keeps_the_full_u16_row_value() {
        let f = TerminusFont::new();
        let g = f.glyph('A', FontWeight::Normal, 32.0);
        assert_eq!(g.cell_w, 16);
        assert_eq!(g.cell_h, 32);
        assert_eq!(g.rows[6], 0x0FF0);
    }

    #[test]
    fn glyph_never_panics_for_any_char() {
        let f = TerminusFont::new();
        for ch in ['日', '😀', char::REPLACEMENT_CHARACTER, '\u{10FFFF}', '\u{0}'] {
            let _ = f.glyph(ch, FontWeight::Normal, 16.0); // must not panic
            let _ = f.glyph(ch, FontWeight::Bold, 16.0);
        }
    }
}
