//! `about:` scheme (packet/attestation-modal): purely in-process, no
//! network, no filesystem. `about:attestations` serves the embedded
//! attestation page (Stele's own short license notice, the generated Cargo
//! dependency/license roster, and Terminus's full OFL-1.1 text, assembled
//! in Task 3); any other `about:<x>`, including the bare `about:` (empty
//! path), degrades to a small, honest "unknown about: page" instead of an
//! error.
//!
//! Same free-function shape as `data::fetch` (no `Fetch` trait — this is a
//! pure function, no state, no I/O). **Total**: `fetch` here NEVER returns
//! `Err` for any input, mirroring the "never vanish" contract
//! `text::glyphs::lookup`/`text::translit::resolve` already guarantee
//! elsewhere (AGENTS.md rule 5) — a malformed/hostile/unknown `about:` URL
//! is strictly better served by a small real page than by propagating a
//! `FetchError` (which would otherwise surface as `dump_text`'s empty
//! string / `dump_png`'s blank 1x1 fallback — see `main.rs`'s own
//! `blank_png` doc comment for that worse shape).
use super::attestations_data;
use super::{FetchError, Request, Response};

/// The hand-authored static shell: headings, section wrappers, and
/// `{{TOKEN}}` placeholders `attestations_page_body` fills in. Kept as a
/// separate asset (not inlined in this file) the same way `data.rs`/`about.rs`
/// itself are kept small — this is markup, not code.
const STATIC_SHELL: &str = include_str!("../../assets/attestations.html");

/// Stele's own SHORT license notice (the standard GPL in-program notice:
/// copyright line + "no warranty" + a pointer to the full text) — NOT the
/// full 35 KB `LICENSE` file, which already satisfies GPL distribution
/// requirements for anyone who clones the source (design doc §2's sizing
/// call). Copyright line matches `REPORT.md`'s own License section.
const STELE_LICENSE_NOTICE: &str = "Stele -- a finished document-web browser for the 486.\n\nCopyright (C) 2026 Tucker McLean.\n\nThis program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.\n\nThis program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>. The full text also travels with the source, in this repository's own LICENSE file.";

/// Terminus Font's full OFL-1.1 text, verbatim, already committed from the
/// Terminus packet (D66) — embedding it here via `include_str!` is the
/// concrete action that resolves D66's own flagged "user-facing attribution
/// lands via the forthcoming attestation modal" judgment call.
const OFL_TEXT: &str = include_str!("../../third_party/terminus-font/OFL.TXT");

/// Split `text` into its blank-line-delimited paragraphs, trimmed, empty
/// ones dropped. The one piece of rendering logic every embedded license
/// text (generated or, like `OFL_TEXT`, hand-copied) goes through before
/// becoming `<p>`s — see the module doc comment's `white-space: pre` note:
/// `layout::inline` always collapses whitespace, so preserving a license
/// text's real paragraph structure has to happen HERE, ahead of layout, not
/// by leaning on a CSS property the engine doesn't enforce yet.
fn split_paragraphs(text: &str) -> Vec<&str> {
    text.split("\n\n").map(str::trim).filter(|p| !p.is_empty()).collect()
}

/// Render `text` as one `<p>` per paragraph (see `split_paragraphs`) — the
/// only shape license/notice text is ever emitted in on this page, never a
/// single `<pre>` block.
fn render_paragraphs(text: &str) -> String {
    let mut out = String::new();
    for para in split_paragraphs(text) {
        out.push_str("<p>");
        out.push_str(&escape_html(para));
        out.push_str("</p>\n");
    }
    out
}

/// The Cargo dependency roster as a `<ul>`'s inner `<li>`s: `"<name>
/// <version> -- <SPDX>"`, one row per `attestations_data::DEPS` entry
/// (generated by `tools/gen-attestations.py`, Task 2).
fn render_roster() -> String {
    let mut out = String::new();
    for d in attestations_data::DEPS {
        out.push_str("<li>");
        out.push_str(&escape_html(d.name));
        out.push(' ');
        out.push_str(&escape_html(d.version));
        out.push_str(" -- ");
        out.push_str(&escape_html(d.spdx));
        out.push_str("</li>\n");
    }
    out
}

/// The deduped license texts, one section per `attestations_data::
/// LICENSE_BLOCKS` entry, headed by the (possibly several) roster names
/// that share it — "see the MIT text below" rather than repeating the same
/// text 13+ times inline (design doc §Design 3).
fn render_license_texts() -> String {
    let mut out = String::new();
    for (i, block) in attestations_data::LICENSE_BLOCKS.iter().enumerate() {
        let credited: Vec<String> = attestations_data::DEPS
            .iter()
            .filter(|d| d.license_block == i)
            .map(|d| format!("{} {}", d.name, d.version))
            .collect();
        out.push_str("<h3>");
        out.push_str(&escape_html(&credited.join(", ")));
        out.push_str("</h3>\n");
        out.push_str(&render_paragraphs(block));
    }
    out
}

/// Assemble the real `about:attestations` page: the static shell with its
/// `{{TOKEN}}` placeholders filled in. Cheap enough to redo on every fetch
/// (this page is navigated to rarely, not perf-sensitive) — no caching.
fn attestations_page_body() -> String {
    STATIC_SHELL
        .replace("{{STELE_NOTICE}}", &render_paragraphs(STELE_LICENSE_NOTICE))
        .replace("{{ROSTER}}", &render_roster())
        .replace("{{LICENSE_TEXTS}}", &render_license_texts())
        .replace("{{OFL_TEXT}}", &render_paragraphs(OFL_TEXT))
}

/// Every `about:` path other than `attestations` (including the bare,
/// empty path `about:` itself) — a small, static "this page doesn't exist"
/// fragment linking back to the one page that does. Matching is exact and
/// case-sensitive on the URL's PATH component (the scheme itself is already
/// lowercased by `Url::scheme()`, but the path is not — `about:Attestations`
/// is therefore deliberately treated as unknown, not as a case-insensitive
/// alias for `about:attestations`; this choice is asserted by a test below).
fn unknown_about_page(path: &str) -> String {
    format!(
        "<!DOCTYPE html><html><body><h1>Unknown about: page</h1><p>There is no about: page named \"{}\". Try <a href=\"about:attestations\">about:attestations</a>.</p></body></html>",
        escape_html(path)
    )
}

/// Minimal HTML-entity escaping for interpolating arbitrary (possibly
/// hostile) URL path text into the unknown-page body — total over any
/// `&str`, including non-ASCII and pathological lengths (no allocation
/// beyond one `String`, no indexing that could panic).
fn escape_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            _ => out.push(c),
        }
    }
    out
}

pub fn fetch(request: &Request) -> Result<Response, FetchError> {
    let path = request.url.path();
    let body = if path == "attestations" {
        attestations_page_body()
    } else {
        unknown_about_page(&path)
    };
    Ok(Response {
        status: 200,
        final_url: request.url.clone(),
        headers: vec![("content-type".to_string(), "text/html".to_string())],
        body: body.into_bytes(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fetch::{Method, Url};

    fn get(url: &str) -> Request {
        Request {
            method: Method::Get,
            url: Url::new(url),
            headers: Vec::new(),
            body: Vec::new(),
        }
    }

    #[test]
    fn fetch_attestations_returns_ok_200_html_nonempty() {
        let resp = fetch(&get("about:attestations")).expect("about: must never error");
        assert_eq!(resp.status, 200);
        assert_eq!(resp.header("content-type"), Some("text/html"));
        assert!(!resp.body.is_empty());
    }

    #[test]
    fn attestations_page_embeds_ofl_verbatim() {
        // Proves third_party/terminus-font/OFL.TXT actually made it into
        // the page (via include_str!), not just referenced by name -- its
        // own distinctive defined-term phrase is a good, specific needle.
        let resp = fetch(&get("about:attestations")).unwrap();
        let body = String::from_utf8_lossy(&resp.body);
        assert!(body.contains("Reserved Font Name"), "OFL-1.1 text missing from body");
    }

    #[test]
    fn attestations_page_embeds_a_real_generated_roster_entry() {
        // Proves the generated roster (tools/gen-attestations.py, Task 2)
        // actually made it into the page, not a stale/empty placeholder.
        let resp = fetch(&get("about:attestations")).unwrap();
        let body = String::from_utf8_lossy(&resp.body);
        let taffy = attestations_data::DEPS.iter().find(|d| d.name == "taffy").expect("DEPS must contain taffy");
        let needle = format!("{} {}", taffy.name, taffy.version);
        assert!(body.contains(&needle), "expected {needle:?} in body");
    }

    #[test]
    fn attestations_page_dom_has_headings_a_big_roster_and_zero_pre_elements() {
        let resp = fetch(&get("about:attestations")).unwrap();
        let body = String::from_utf8_lossy(&resp.body).into_owned();
        let dom = crate::dom::parser::parse(&body);

        fn count_tag(d: &crate::dom::Dom, id: crate::dom::NodeId, tag: &str, out: &mut usize) {
            if let Some(el) = d.node(id).element() {
                if el.name.as_str() == tag {
                    *out += 1;
                }
                for &c in &el.children {
                    count_tag(d, c, tag, out);
                }
            }
        }
        fn find_all(d: &crate::dom::Dom, id: crate::dom::NodeId, tag: &str, out: &mut Vec<crate::dom::NodeId>) {
            if let Some(el) = d.node(id).element() {
                if el.name.as_str() == tag {
                    out.push(id);
                }
                for &c in &el.children {
                    find_all(d, c, tag, out);
                }
            }
        }

        let mut h1_count = 0;
        count_tag(&dom, dom.root(), "h1", &mut h1_count);
        assert!(h1_count >= 1, "expected at least one <h1>");

        let mut uls = Vec::new();
        find_all(&dom, dom.root(), "ul", &mut uls);
        assert!(!uls.is_empty(), "expected at least one <ul>");
        let max_li = uls
            .iter()
            .map(|&ul_id| {
                let el = dom.node(ul_id).element().unwrap();
                el.children
                    .iter()
                    .filter(|&&c| dom.node(c).element().map(|e| e.name.as_str() == "li").unwrap_or(false))
                    .count()
            })
            .max()
            .unwrap_or(0);
        assert!(max_li > 5, "expected a <ul> with more than 5 <li> children (roster sanity), got {max_li}");

        // The `white-space: pre` gap (module doc comment): this page must
        // NEVER rely on <pre> for license-text structure -- a durable
        // regression guard against someone "helpfully" reintroducing it.
        let mut pre_count = 0;
        count_tag(&dom, dom.root(), "pre", &mut pre_count);
        assert_eq!(pre_count, 0, "about:attestations must never use <pre> -- layout::inline always collapses its whitespace");
    }

    #[test]
    fn attestations_page_body_parses_into_a_non_degenerate_dom() {
        // Totality smoke test, mirroring REPORT.md's fuzz-totality
        // discipline for the rest of the pipeline: the assembled body is
        // valid enough UTF-8 HTML that parsing it doesn't silently yield an
        // (almost) empty tree.
        let resp = fetch(&get("about:attestations")).unwrap();
        let body = String::from_utf8_lossy(&resp.body).into_owned();
        let dom = crate::dom::parser::parse(&body);
        assert!(dom.len() > 20, "expected a substantial DOM, got {} nodes", dom.len());
    }

    #[test]
    fn fetch_bare_about_scheme_is_the_unknown_page() {
        let resp = fetch(&get("about:")).expect("about: must never error");
        assert_eq!(resp.status, 200);
        let body = String::from_utf8_lossy(&resp.body);
        assert!(body.contains("Unknown about:"), "body: {body}");
    }

    #[test]
    fn fetch_path_case_is_significant_about_attestations_capitalized_is_unknown() {
        // Deliberate choice (documented on `unknown_about_page`): the
        // scheme is lowercased by `Url::scheme()`, but the PATH is not, so
        // `about:Attestations` does NOT alias `about:attestations`.
        let resp = fetch(&get("about:Attestations")).expect("about: must never error");
        let body = String::from_utf8_lossy(&resp.body);
        assert!(
            body.contains("Unknown about:"),
            "about:Attestations (capitalized path) must be treated as unknown, got: {body}"
        );
    }

    #[test]
    fn fetch_is_total_over_hostile_about_inputs() {
        let long_garbage: String = "x".repeat(10_000);
        let inputs: &[&str] = &[
            "about:",
            "about:blank",
            "about:xyz",
            "about:Attestations",
            &long_garbage,
            "about:\u{2603}\u{1F4A5}\u{975E}ASCII", // snowman, boom emoji, non-ASCII CJK
            "about:attestations/../../etc/passwd",
            "about:attestations?x=1#frag",
        ];
        for input in inputs {
            let url = if input.starts_with("about:") {
                input.to_string()
            } else {
                format!("about:{input}")
            };
            let resp = fetch(&get(&url)).unwrap_or_else(|e| panic!("about: fetch must never error, input {url:?}: {e:?}"));
            assert_eq!(resp.status, 200, "input {url:?}");
            assert!(!resp.body.is_empty(), "input {url:?}");
        }
    }
}
