//! Hand-verified assertions against the GENERATED `attestations_data`
//! module (packet/attestation-modal, Task 2). Deliberately a SEPARATE file
//! from `attestations_data.rs` itself -- that file is regenerated by
//! `tools/gen-attestations.py` and hand-written tests placed inside it
//! would be silently overwritten the next time the tool runs.
//!
//! The specific facts pinned here were read directly from `cargo metadata
//! --filter-platform targets/i486-monolith-linux-musl.json` before this
//! generator existed (design doc's "Current state" section) -- this is the
//! failing-test-first step (Task 2 plan step 2/3/4/5): these assertions are
//! true of the REAL graph, not aspirational.
use super::attestations_data::{DEPS, LICENSE_BLOCKS};

fn find(name: &str) -> &'static super::attestations_data::DepEntry {
    DEPS.iter()
        .find(|d| d.name == name)
        .unwrap_or_else(|| panic!("DEPS has no entry for {name:?}"))
}

#[test]
fn taffy_is_credited_as_mit() {
    // taffy 0.13.0 ships no LICENSE* file in its published crate -- its
    // text is a pinned upstream fallback (see the generator's doc comment)
    // but its SPDX id is still the crate's own real `license = "MIT"`.
    assert_eq!(find("taffy").spdx, "MIT");
}

#[test]
fn slotmap_is_credited_as_zlib_its_sole_license() {
    // slotmap's Cargo.toml declares `license = "Zlib"` -- no MIT/Apache-2.0
    // alternative exists, unlike nearly everything else in this roster.
    assert_eq!(find("slotmap").spdx, "Zlib");
}

#[test]
fn build_only_and_windows_only_crates_are_excluded() {
    // proc-macro/build-script-only (never linked into stele-i486):
    for excluded in ["serde_derive", "syn", "quote", "proc-macro2", "unicode-ident", "version_check"] {
        assert!(
            DEPS.iter().all(|d| d.name != excluded),
            "{excluded} must be excluded (build-time-only), but DEPS contains it"
        );
    }
    // Windows-only cfg deps of rustix/errno -- never compiled for the i486
    // musl target at all (cargo metadata --filter-platform already drops
    // them from the graph; this is a durable regression guard).
    for excluded in ["windows-sys", "windows-link"] {
        assert!(
            DEPS.iter().all(|d| d.name != excluded),
            "{excluded} must be excluded (Windows-only cfg), but DEPS contains it"
        );
    }
}

#[test]
fn rustix_linux_raw_sys_and_serde_share_one_deduped_license_block() {
    // Confirmed real (not theoretical): these three crates' LICENSE-MIT
    // files are byte-identical -- the generator's content-hash dedup
    // collapses them into a single LICENSE_BLOCKS entry, referenced three
    // times, rather than storing the same ~1 KB text three times over.
    let rustix = find("rustix").license_block;
    let linux_raw_sys = find("linux-raw-sys").license_block;
    let serde = find("serde").license_block;
    assert_eq!(rustix, linux_raw_sys);
    assert_eq!(rustix, serde);
}

#[test]
fn every_license_block_over_500_bytes_has_more_than_one_paragraph() {
    // Structural sanity check that the generator's source texts really do
    // carry their original blank-line paragraph structure through (not a
    // no-op pass-through of one giant blob) -- `fetch::about`'s Task 3
    // render step depends on being able to split each block into multiple
    // `<p>`s this way (the `white-space: pre` gap, see `about.rs`'s doc
    // comment).
    for (i, block) in LICENSE_BLOCKS.iter().enumerate() {
        if block.len() > 500 {
            let paragraphs: Vec<&str> = block.split("\n\n").filter(|p| !p.trim().is_empty()).collect();
            assert!(
                paragraphs.len() > 1,
                "LICENSE_BLOCKS[{i}] is {} bytes but splits into only {} paragraph(s)",
                block.len(),
                paragraphs.len()
            );
        }
    }
}

#[test]
fn deps_len_matches_the_real_i486_filtered_runtime_dependency_count() {
    // Hand-counted from `cargo metadata --filter-platform
    // targets/i486-monolith-linux-musl.json`'s resolved graph, walked via
    // Normal-kind edges only, proc-macro subtrees excluded (packet/
    // attestation-modal design doc's own trace, reconfirmed against the
    // real graph at generator-authoring time -- NOT copied from the design
    // doc's own hand-derived prose count):
    //   adler2, arrayvec, bitflags(1.3.2), bitflags(2.13.1), cfg-if,
    //   color_quant, crc32fast, errno, fdeflate, flate2, gif, jpeg-decoder,
    //   libc, linux-raw-sys, miniz_oxide, png, rustix, serde, serde_core,
    //   simd-adler32, slotmap, smallvec, taffy, weezl = 24.
    assert_eq!(DEPS.len(), 24, "DEPS: {:#?}", DEPS.iter().map(|d| (d.name, d.version)).collect::<Vec<_>>());
}

#[test]
fn every_dep_license_block_index_is_in_range() {
    for d in DEPS {
        assert!(
            d.license_block < LICENSE_BLOCKS.len(),
            "{} {} has out-of-range license_block {}",
            d.name,
            d.version,
            d.license_block
        );
    }
}
