#!/usr/bin/env python3
"""Generate `attestation/dependency-manifest.txt` from `Cargo.lock` (charter
C8 / build-brief A6: "cargo audit-clean vendored deps ... attested
provenance"). A pure text transform of Cargo.lock's own per-dependency
sha256 checksums into a diff-stable, reviewable roster -- no network, no
cargo invocation, so it runs anywhere Python does (this sandbox included).

## What this does

1. Parses `Cargo.lock` (TOML, hand-rolled parser -- no `tomllib` dependency
   assumed present) for every `[[package]]` table.
2. Emits one line per package that has a `checksum` field (registry
   dependencies only -- the local workspace member `stele` itself has no
   checksum and is intentionally excluded: there is nothing to attest about
   your own source, and Cargo.lock does not record one).
3. Sorts by (name, version) for determinism -- Cargo.lock is already close
   to this order but is not guaranteed to stay that way.
4. `--write` regenerates `attestation/dependency-manifest.txt` in place.
   `--check` regenerates to a temp file and diffs against the committed
   copy, exiting non-zero on drift (this is what accept.sh A6b runs).

## Why this, not `cargo vendor` + a vendor/ diff

`cargo vendor` needs network + cargo (both absent from this sandbox --
confirmed: no cargo/rustc on PATH). The checksums Cargo.lock already
records are exactly what `cargo vendor`'s own `.cargo-checksum.json` files
would contain per-crate; projecting them out of the lockfile gets the same
attestation value (a reviewable, diffable, hash-pinned dependency roster)
without requiring the vendor step to run first. `tools/vendor.sh` (this
packet) does the full `cargo vendor` for whoever next has cargo+network;
this script's manifest is intentionally independent of whether that has
happened yet.
"""
import argparse
import re
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LOCKFILE = REPO_ROOT / "Cargo.lock"
MANIFEST = REPO_ROOT / "attestation" / "dependency-manifest.txt"

HEADER = (
    "# Generated by tools/gen-dependency-manifest.py from Cargo.lock. Do not "
    "hand-edit.\n"
    "# One line per registry dependency: name version sha256.\n"
    "# The local workspace member (stele itself) has no checksum and is "
    "excluded.\n"
)


def parse_lockfile_packages(text):
    """Hand-rolled TOML parse of Cargo.lock's flat `[[package]]` tables.

    Cargo.lock is machine-generated and never contains nested tables, arrays
    of tables other than `[[package]]`, or multiline strings inside a
    package block, so a per-block key=value scan is exact for this file
    without pulling in a TOML library.
    """
    packages = []
    current = None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped == "[[package]]":
            if current is not None:
                packages.append(current)
            current = {}
            continue
        if current is None:
            continue
        if stripped.startswith("["):
            # Entering some other table (e.g. [[patch.unused]]) -- close out.
            packages.append(current)
            current = None
            continue
        m = re.match(r'^(\w+)\s*=\s*"(.*)"\s*$', stripped)
        if m:
            current[m.group(1)] = m.group(2)
    if current is not None:
        packages.append(current)
    return packages


def build_manifest_lines(packages):
    lines = []
    for pkg in packages:
        checksum = pkg.get("checksum")
        if not checksum:
            continue  # local workspace member; nothing to attest
        name = pkg["name"]
        version = pkg["version"]
        lines.append(f"{name} {version} {checksum}\n")
    lines.sort()
    return lines


def render(packages):
    return HEADER + "".join(build_manifest_lines(packages))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--write", action="store_true", help="regenerate the committed manifest"
    )
    mode.add_argument(
        "--check", action="store_true", help="fail if the manifest is stale"
    )
    args = parser.parse_args()

    if not LOCKFILE.exists():
        print(f"error: {LOCKFILE} not found", file=sys.stderr)
        return 1

    packages = parse_lockfile_packages(LOCKFILE.read_text())
    if not packages:
        print(f"error: no [[package]] entries parsed from {LOCKFILE}", file=sys.stderr)
        return 1

    rendered = render(packages)

    if args.write:
        MANIFEST.parent.mkdir(parents=True, exist_ok=True)
        MANIFEST.write_text(rendered)
        print(f"wrote {MANIFEST} ({len(packages)} packages scanned)")
        return 0

    # --check
    if not MANIFEST.exists():
        print(f"error: {MANIFEST} does not exist -- run with --write first", file=sys.stderr)
        return 1
    with tempfile.NamedTemporaryFile("w", suffix=".txt", delete=False) as tmp:
        tmp.write(rendered)
        tmp_path = Path(tmp.name)
    try:
        committed = MANIFEST.read_text()
        if committed != rendered:
            print(f"error: {MANIFEST} is stale relative to {LOCKFILE}", file=sys.stderr)
            print(f"  regenerate with: python3 {Path(__file__).name} --write", file=sys.stderr)
            return 1
        print(f"ok: {MANIFEST} matches {LOCKFILE} ({len(packages)} packages)")
        return 0
    finally:
        tmp_path.unlink(missing_ok=True)


if __name__ == "__main__":
    sys.exit(main())
